### PR TITLE
Update tmc2130.c

### PR DESCRIPTION
**Pull request by SNDR0**
Bug. Now it's  OK and coolconf register works ok from -64..63

### CODE REVIEW

**Comment by chriswal** [comment]
Please before you fix something please check if it is really an error .
the coolconf register has 26 bit. Look at the tmc2130 data sheet. so it should be unsigned.
perhaps there is elswhere an error if it doesnt work.

**Comment by SNDR0** [comment]
tmc2130_wr(axis, TMC2130_REG_COOLCONF, (((int32_t)__sg_thr(axis)) << 16));
it's unsigned but you are writing only  stallGuard2 threshold value ( that
is signed). so you have a number signed, shifted of 16. so your little
number from -64 to +63 is shifted  from bit 16 to 22. for me is a bug.

Il giorno mar 30 apr 2019 alle ore 02:37 chriswal <notifications@github.com>
ha scritto:

**Comment by chriswal** [comment]
the stallguard threshold is a signed value in an unsigned register. i attached the picture of the register
coolconf

**Comment by SNDR0** [comment]
yes. we see the same datasheet. ok. i understand my mistake

Il giorno mar 30 apr 2019 alle ore 03:06 chriswal <notifications@github.com>
ha scritto:

**Comment by SNDR0** [comment]
my mistake newbie with c++, but I love it

**Comment by SNDR0** [comment]
added 2 cap 104 and now finally works like a charm... no blinking leds, no
noise.. wonderfull!!!. thanks

Il giorno mar 30 apr 2019 alle ore 03:24 Alessandro Negri <
sandrux1978@gmail.com> ha scritto:

**Pull request closed without merging**
