### PR TITLE
Update stepper.cpp

### PR DESCRIPTION
**Pull request by SNDR0**
part 1/2 changes for homing selector, next is config.h

### CODE REVIEW

**Comment by chriswal** [comment]
your homing in the wrong direction homing sequence is to the motor

**Comment by SNDR0** [comment]
used 1.0.3 , 1.0.4 and 1.0.5 originals  and selector never homed to right,
always to the left with bad clicking and often idler not homing correctly.
after that prints with mmu2 are ok. homing to the left is more quickly and
ready to filament 1..

Il giorno mar 30 apr 2019 alle ore 00:51 chriswal <notifications@github.com>
ha scritto:

**Comment by chriswal** [comment]
The problem of not homing is the 74hc595 register. it needs buffer capacitors on the power pins.
the register outputs random values on power problems ( that leads to flickering leds and hissing motors). the stepper drivers are also connected to the register.

**Comment by SNDR0** [comment]
i saw the scheme.. i will try to add capacitors for filtering.. main
problem for homing is  delay(50); after move. it create a bug when you move
1 step per time and create a mechanical resonance in the stepper motor that
cause stepping front and back with nonsense.
for the noise i suspect that the configuration of tmc2130 (auto scaling e
auto tuning pwm ) create noise amplified from steppers, next problem to
solve after enstops...

Il giorno mar 30 apr 2019 alle ore 01:18 chriswal <notifications@github.com>
ha scritto:

**Comment by SNDR0** [comment]
closing and reopening with correct side homing

**Comment by chriswal** [comment]
The back move is intentionally from the firmware if it got stuck. the sg value drops to 0 because of the register ( so it thiks its stalled) then makes a back move and then again forward (5 times on the actual firmware) if this is not enough it cant reach the home position. After reaching the home position the selector goes to filament 1 (i dont remember the steps) As stallguard is not checked for this move it hits the wall opposing the motor

**Comment by SNDR0** [comment]
fully functional selector (correct side)  and idler homing. noise limited
to very low level setting pulley in homing and idle to 0. updating in this
moment

Il giorno mar 30 apr 2019 alle ore 01:44 chriswal <notifications@github.com>
ha scritto:

**Pull request closed without merging**
